const numberShadow = value => ({ shadow: { type: 'math_number', fields: { NUM: value } } });
const currentCard = () => ({ block: { type: 'card_current' } });
const selectedCard = () => ({ block: { type: 'card_selected' } });
const cardById = id => ({ block: { type: 'card_by_id', fields: { CARD_ID: id } } });
const currentEquipment = () => ({ block: { type: 'equipment_current' } });

export const toolbox = {
  kind: 'categoryToolbox',
  contents: [
    {
      kind: 'category',
      name: '触发',
      colour: 24,
      contents: [
        { kind: 'block', type: 'trigger_on_play' },
        { kind: 'block', type: 'trigger_event_apply' },
        { kind: 'block', type: 'trigger_status_exists' },
        { kind: 'block', type: 'trigger_tag_exists' },
        { kind: 'block', type: 'trigger_on_friendly_turn_start' },
        { kind: 'block', type: 'trigger_on_enemy_turn_start' },
        { kind: 'block', type: 'trigger_on_phys_damage' },
        { kind: 'block', type: 'trigger_on_any_damage' },
        { kind: 'block', type: 'trigger_on_damage_from' },
        { kind: 'block', type: 'trigger_on_card_used' },
        { kind: 'block', type: 'trigger_on_equipment_triggered' },
        { kind: 'block', type: 'trigger_on_equipment_destroyed' },
        { kind: 'block', type: 'trigger_on_resource_spent', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'trigger_on_player_stat_changed' },
        { kind: 'block', type: 'trigger_on_destroy' },
        { kind: 'block', type: 'trigger_hand_owner_turn_start' },
        { kind: 'block', type: 'trigger_discard_owner_turn_start' },
        { kind: 'block', type: 'trigger_deck_owner_turn_start' },
        { kind: 'block', type: 'trigger_on_event' },
        { kind: 'block', type: 'trigger_manual' },
        { kind: 'block', type: 'response_declare' },
        { kind: 'block', type: 'equipment_any_turn_start' },
        { kind: 'block', type: 'equipment_owner_turn_start' },
        { kind: 'block', type: 'equipment_owner_turn_ready', inputs: { MIN_TURNS: numberShadow(1) } },
        { kind: 'block', type: 'equipment_enemy_turn_start' },
        { kind: 'block', type: 'equipment_damage_taken' },
        { kind: 'block', type: 'equipment_manual_trigger', inputs: { MAX_USES: numberShadow(0) } },
        { kind: 'block', type: 'aura_enemy_elixir_recovery', inputs: { AMOUNT: numberShadow(-1) } },
        { kind: 'block', type: 'passive_fatal_set_health_exile', inputs: { HEALTH: numberShadow(5) } },
        { kind: 'block', type: 'counter_dodge', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'counter_nazar' },
        { kind: 'block', type: 'counter_equip_protect', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'counter_negate_skill' },
        { kind: 'block', type: 'counter_block_enemy_attacks', inputs: { DURATION: numberShadow(1) } },
        { kind: 'block', type: 'counter_set_invincible_then_die' },
      ],
    },
    {
      kind: 'category',
      name: '目标',
      colour: 55,
      contents: [
        { kind: 'block', type: 'target_self' },
        { kind: 'block', type: 'target_teammate' },
        { kind: 'block', type: 'target_friendly' },
        { kind: 'block', type: 'target_enemy' },
        { kind: 'block', type: 'target_all_enemies' },
        { kind: 'block', type: 'target_both' },
        { kind: 'block', type: 'target_random_friendly' },
        { kind: 'block', type: 'target_random_enemy' },
        { kind: 'block', type: 'target_random_player' },
        { kind: 'block', type: 'target_random_side' },
        { kind: 'block', type: 'target_event_target' },
        { kind: 'block', type: 'target_event_source' },
        { kind: 'block', type: 'target_damage_source' },
        { kind: 'block', type: 'target_last_actor' },
        { kind: 'block', type: 'target_choice' },
        { kind: 'block', type: 'target_team_var_scope' },
        { kind: 'block', type: 'target_global_var_scope' },
        {
          kind: 'block',
          type: 'target_card_owner',
        },
        {
          kind: 'block',
          type: 'action_request_target',
          inputs: {
            TARGETS: { block: { type: 'target_enemy' } },
          },
        },
        { kind: 'block', type: 'action_request_card', inputs: { TARGET: { block: { type: 'target_self' } } } },
        { kind: 'block', type: 'action_request_optional_card', inputs: { TARGET: { block: { type: 'target_self' } } } },
        {
          kind: 'block',
          type: 'action_request_cards',
          inputs: {
            TARGET: { block: { type: 'target_self' } },
            MIN_COUNT: numberShadow(1),
            MAX_COUNT: numberShadow(3),
          },
        },
        { kind: 'block', type: 'action_request_confirm' },
      ],
    },
    {
      kind: 'category',
      name: '伤害与回复',
      colour: 350,
      contents: [
        {
          kind: 'block',
          type: 'action_damage',
          inputs: { AMOUNT: numberShadow(6) },
        },
        {
          kind: 'block',
          type: 'action_damage_multi',
          inputs: {
            AMOUNT: numberShadow(2),
            TIMES: numberShadow(2),
          },
        },
        {
          kind: 'block',
          type: 'action_direct_damage',
          inputs: { AMOUNT: numberShadow(1) },
        },
        { kind: 'block', type: 'action_heal', inputs: { AMOUNT: numberShadow(4) } },
        { kind: 'block', type: 'action_set_health', inputs: { AMOUNT: numberShadow(20) } },
        { kind: 'block', type: 'action_add_armor', inputs: { AMOUNT: numberShadow(2) } },
        { kind: 'block', type: 'action_remove_armor', inputs: { AMOUNT: numberShadow(2) } },
        { kind: 'block', type: 'action_set_armor', inputs: { AMOUNT: numberShadow(0) } },
        { kind: 'block', type: 'action_dodge_this' },
        { kind: 'block', type: 'action_dodge_permanent', inputs: { AMOUNT: numberShadow(1) } },
      ],
    },
    {
      kind: 'category',
      name: '状态与标签',
      colour: 300,
      contents: [
        { kind: 'block', type: 'action_poison', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_burn', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_vulnus', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_toxic', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_status_add_named', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_status_remove_named' },
        { kind: 'block', type: 'action_tag_add_named' },
        { kind: 'block', type: 'action_tag_remove_named' },
        { kind: 'block', type: 'action_tag_add_id' },
        { kind: 'block', type: 'action_tag_remove_id' },
        { kind: 'block', type: 'action_add_tag' },
        { kind: 'block', type: 'action_remove_tag' },
        { kind: 'block', type: 'action_clear_buffs' },
        { kind: 'block', type: 'action_clear_debuffs' },
        { kind: 'block', type: 'action_clear_all_effects' },
        { kind: 'block', type: 'action_clear_status' },
      ],
    },
    {
      kind: 'category',
      name: '资源与牌堆',
      colour: 185,
      contents: [
        { kind: 'block', type: 'action_gain_e', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_gain_m', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_cost_e', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_cost_m', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_mod_e_regen', inputs: { AMOUNT: numberShadow(-1) } },
        { kind: 'block', type: 'action_mod_m_regen', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_mod_draw', inputs: { AMOUNT: numberShadow(-1) } },
        { kind: 'block', type: 'action_draw', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_discard', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_discard_choice_then_draw' },
        { kind: 'block', type: 'action_choose_from_deck' },
        { kind: 'block', type: 'action_choose_from_discard' },
        { kind: 'block', type: 'action_choose_from_exile' },
        { kind: 'block', type: 'action_reveal_hand' },
        { kind: 'block', type: 'action_steal_card' },
      ],
    },
    {
      kind: 'category',
      name: '装备与限制',
      colour: 220,
      contents: [
        { kind: 'block', type: 'action_destroy_random_equip' },
        { kind: 'block', type: 'action_destroy_all_equip' },
        { kind: 'block', type: 'action_destroy_all_field_equip' },
        { kind: 'block', type: 'action_destroy_equipment_choice_or_first' },
        { kind: 'block', type: 'action_destroy_all_destroyable_equipment' },
        { kind: 'block', type: 'action_equip_this_card' },
        { kind: 'block', type: 'action_add_equipment_to_zone', inputs: { CARD: cardById('Leaf'), TARGET: { block: { type: 'target_self' } } } },
        { kind: 'block', type: 'action_equipment_prop_set', inputs: { EQUIPMENT: currentEquipment(), VALUE: numberShadow(1) } },
        { kind: 'block', type: 'action_equipment_prop_add', inputs: { EQUIPMENT: currentEquipment(), AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_player_prop_set', inputs: { TARGET: { block: { type: 'target_self' } }, VALUE: numberShadow(1) } },
        { kind: 'block', type: 'action_player_prop_add', inputs: { TARGET: { block: { type: 'target_self' } }, AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_max_health_add', inputs: { TARGET: { block: { type: 'target_self' } }, AMOUNT: numberShadow(10) } },
        { kind: 'block', type: 'action_max_elixir_add', inputs: { TARGET: { block: { type: 'target_self' } }, AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_max_magic_add', inputs: { TARGET: { block: { type: 'target_self' } }, AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_destroy_self_equipment', inputs: { EQUIPMENT: currentEquipment() } },
        { kind: 'block', type: 'action_equip_protection', inputs: { EQUIPMENT: currentEquipment() } },
        { kind: 'block', type: 'action_remove_equip_protection' },
        { kind: 'block', type: 'action_block_action' },
        { kind: 'block', type: 'action_block_card_type', inputs: { DURATION: numberShadow(1) } },
        { kind: 'block', type: 'action_force_card_type', inputs: { DURATION: numberShadow(1) } },
        { kind: 'block', type: 'action_nullify_current_card' },
        { kind: 'block', type: 'action_invincible' },
        { kind: 'block', type: 'action_untargetable' },
        { kind: 'block', type: 'action_skip_turn' },
        { kind: 'block', type: 'action_extra_turn' },
        { kind: 'block', type: 'action_force_end_turn' },
      ],
    },
    {
      kind: 'category',
      name: '卡牌操作',
      colour: 260,
      contents: [
        { kind: 'block', type: 'card_current' },
        { kind: 'block', type: 'card_selected' },
        { kind: 'block', type: 'card_event_card' },
        { kind: 'block', type: 'card_last_created' },
        { kind: 'block', type: 'card_by_id' },
        { kind: 'block', type: 'card_in_hand_at', inputs: { TARGET: { block: { type: 'target_self' } }, INDEX: numberShadow(1) } },
        { kind: 'block', type: 'card_in_deck_at', inputs: { TARGET: { block: { type: 'target_self' } }, INDEX: numberShadow(1) } },
        { kind: 'block', type: 'card_in_discard_at', inputs: { TARGET: { block: { type: 'target_self' } }, INDEX: numberShadow(1) } },
        { kind: 'block', type: 'card_in_exile_at', inputs: { TARGET: { block: { type: 'target_self' } }, INDEX: numberShadow(1) } },
        { kind: 'block', type: 'card_selected_at', inputs: { INDEX: numberShadow(1) } },
        { kind: 'block', type: 'equipment_current' },
        { kind: 'block', type: 'equipment_selected' },
        { kind: 'block', type: 'equipment_event_equipment' },
        { kind: 'block', type: 'control_for_each_equipment', inputs: { TARGET: { block: { type: 'target_self' } }, CARD: cardById('Leaf') } },
        { kind: 'block', type: 'action_fission', inputs: { TIMES: numberShadow(2) } },
        { kind: 'block', type: 'action_fusion', inputs: { MIN_COUNT: numberShadow(2), MAX_COUNT: numberShadow(3) } },
        { kind: 'block', type: 'action_multiply_next_damage', inputs: { MULTIPLIER: numberShadow(2) } },
        { kind: 'block', type: 'action_reduce_next_cost', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_increase_next_cost', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_transform_card' },
        { kind: 'block', type: 'action_copy_card' },
        { kind: 'block', type: 'action_copy_choice_with_discount', inputs: { DISCOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_card_fission_add', inputs: { AMOUNT: numberShadow(2) } },
        { kind: 'block', type: 'action_card_fission_set', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_card_fusion_add', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_card_fusion_set', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_card_discount_set', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_card_prop_set', inputs: { VALUE: numberShadow(0) } },
        { kind: 'block', type: 'action_card_prop_add', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_card_prop_mul', inputs: { MULTIPLIER: numberShadow(2) } },
        { kind: 'block', type: 'action_card_damage_multiply', inputs: { MULTIPLIER: numberShadow(2) } },
        { kind: 'block', type: 'action_give_card_to_hand', inputs: { CARD: cardById('Basic') } },
        { kind: 'block', type: 'action_give_card_to_deck', inputs: { CARD: cardById('Basic') } },
        { kind: 'block', type: 'action_give_card_to_discard', inputs: { CARD: cardById('Basic') } },
        { kind: 'block', type: 'action_remove_specific_card', inputs: { CARD: cardById('Basic') } },
        { kind: 'block', type: 'action_clear_card_tags' },
        { kind: 'block', type: 'action_exile_this' },
        { kind: 'block', type: 'action_move_to_hand', inputs: { CARD: { block: { type: 'card_selected' } }, TARGET: { block: { type: 'target_self' } } } },
        { kind: 'block', type: 'action_move_to_discard' },
        { kind: 'block', type: 'action_move_to_deck' },
      ],
    },
    {
      kind: 'category',
      name: '变量',
      colour: 32,
      contents: [
        { kind: 'block', type: 'value_var' },
        { kind: 'block', type: 'value_list_var' },
        { kind: 'block', type: 'value_list_create', inputs: { A: numberShadow(1), B: numberShadow(2), C: numberShadow(3) } },
        { kind: 'block', type: 'value_list_literal' },
        { kind: 'block', type: 'value_zone_list', inputs: { TARGET: { block: { type: 'target_enemy' } } } },
        { kind: 'block', type: 'value_list_length' },
        { kind: 'block', type: 'value_list_item', inputs: { INDEX: numberShadow(1) } },
        { kind: 'block', type: 'card_from_var' },
        { kind: 'block', type: 'value_damage_source' },
        { kind: 'block', type: 'value_damage_amount' },
        { kind: 'block', type: 'value_choice_target' },
        { kind: 'block', type: 'value_choice_confirmed' },
        { kind: 'block', type: 'value_timer_remaining' },
        { kind: 'block', type: 'value_selected_card_index' },
        { kind: 'block', type: 'value_loop_index' },
        { kind: 'block', type: 'value_selected_cards_count' },
        { kind: 'block', type: 'value_card_property' },
        { kind: 'block', type: 'value_card_tag_count', inputs: { CARD: currentCard() } },
        { kind: 'block', type: 'value_card_def_property', inputs: { CARD: cardById('Basic') } },
        { kind: 'block', type: 'value_card_def_tags', inputs: { CARD: cardById('Basic') } },
        { kind: 'block', type: 'value_equipment_property', inputs: { EQUIPMENT: currentEquipment() } },
        { kind: 'block', type: 'value_player_property', inputs: { TARGET: { block: { type: 'target_self' } } } },
        { kind: 'block', type: 'condition_var_compare', inputs: { VALUE: numberShadow(0) } },
        { kind: 'block', type: 'condition_list_contains' },
        { kind: 'block', type: 'action_var_set', inputs: { VALUE: numberShadow(0) } },
        { kind: 'block', type: 'action_list_set' },
        { kind: 'block', type: 'action_list_append' },
        { kind: 'block', type: 'action_list_insert', inputs: { INDEX: numberShadow(1) } },
        { kind: 'block', type: 'action_list_delete', inputs: { INDEX: numberShadow(1) } },
        { kind: 'block', type: 'action_list_clear' },
        { kind: 'block', type: 'action_countdown_var', inputs: { DURATION: numberShadow(2) } },
        { kind: 'block', type: 'action_var_add', inputs: { VALUE: numberShadow(1) } },
        { kind: 'block', type: 'action_var_sub', inputs: { VALUE: numberShadow(1) } },
        { kind: 'block', type: 'action_var_mul', inputs: { VALUE: numberShadow(2) } },
        { kind: 'block', type: 'action_var_div', inputs: { VALUE: numberShadow(2) } },
        { kind: 'block', type: 'action_batch_var_add', inputs: { VALUE: numberShadow(1) } },
        { kind: 'block', type: 'action_batch_var_sub', inputs: { VALUE: numberShadow(1) } },
      ],
    },
    {
      kind: 'category',
      name: '逻辑与数值',
      colour: 120,
      contents: [
        { kind: 'block', type: 'control_if' },
        { kind: 'block', type: 'control_if_else' },
        { kind: 'block', type: 'control_repeat', inputs: { TIMES: numberShadow(2) } },
        { kind: 'block', type: 'control_repeat_until' },
        { kind: 'block', type: 'control_for_each_selected_card' },
        { kind: 'block', type: 'control_for_each' },
        { kind: 'block', type: 'control_for_each_list' },
        { kind: 'block', type: 'control_for_each_equipment', inputs: { TARGET: { block: { type: 'target_self' } }, CARD: cardById('Leaf') } },
        { kind: 'block', type: 'control_timed_effect', inputs: { DURATION: numberShadow(2) } },
        { kind: 'block', type: 'control_random' },
        { kind: 'block', type: 'control_break' },
        { kind: 'block', type: 'control_continue' },
        { kind: 'block', type: 'condition_compare', inputs: { A: numberShadow(0), B: numberShadow(0) } },
        { kind: 'block', type: 'condition_hand_size_compare', inputs: { TARGET: { block: { type: 'target_enemy' } }, VALUE: numberShadow(1) } },
        { kind: 'block', type: 'condition_hand_limit_compare', inputs: { TARGET: { block: { type: 'target_enemy' } }, VALUE: numberShadow(7) } },
        { kind: 'block', type: 'condition_has_status_named' },
        { kind: 'block', type: 'condition_has_tag' },
        { kind: 'block', type: 'condition_damage_source_relation' },
        { kind: 'block', type: 'condition_target_attribute', inputs: { VALUE: numberShadow(0) } },
        { kind: 'block', type: 'condition_and_or' },
        { kind: 'block', type: 'condition_not' },
        { kind: 'block', type: 'raw_effect_json' },
        { kind: 'block', type: 'value_target_attribute' },
        { kind: 'block', type: 'value_hand_size', inputs: { TARGET: { block: { type: 'target_enemy' } } } },
        { kind: 'block', type: 'value_hand_limit', inputs: { TARGET: { block: { type: 'target_enemy' } } } },
        { kind: 'block', type: 'value_zone_count', inputs: { TARGET: { block: { type: 'target_self' } } } },
        { kind: 'block', type: 'value_incoming_damage' },
        { kind: 'block', type: 'value_last_damage' },
        { kind: 'block', type: 'value_status_count' },
        { kind: 'block', type: 'value_equipment_count_named', inputs: { CARD: cardById('Disc') } },
        {
          kind: 'block',
          type: 'value_math_op',
          inputs: {
            A: numberShadow(0),
            B: numberShadow(0),
          },
        },
        {
          kind: 'block',
          type: 'value_round',
          inputs: { VALUE: numberShadow(0) },
        },
        {
          kind: 'block',
          type: 'value_min_max',
          inputs: {
            A: numberShadow(0),
            B: numberShadow(0),
          },
        },
        {
          kind: 'block',
          type: 'value_random',
          inputs: {
            MIN: numberShadow(1),
            MAX: numberShadow(10),
          },
        },
      ],
    },
    { kind: 'sep' },
    { kind: 'category', name: '自定义过程', custom: 'PROCEDURE', colour: 285 },
  ],
};

const triggerBlock = (type, inputs = null) => {
  const block = { kind: 'block', type };
  if (inputs) block.inputs = inputs;
  return block;
};

const CARD_TRIGGER_BLOCKS = [
  triggerBlock('trigger_on_play'),
  triggerBlock('trigger_on_friendly_turn_start'),
  triggerBlock('trigger_on_enemy_turn_start'),
  triggerBlock('trigger_on_phys_damage'),
  triggerBlock('trigger_on_any_damage'),
  triggerBlock('trigger_on_destroy'),
  triggerBlock('trigger_hand_owner_turn_start'),
  triggerBlock('trigger_discard_owner_turn_start'),
  triggerBlock('trigger_deck_owner_turn_start'),
  triggerBlock('trigger_on_event'),
  triggerBlock('trigger_manual'),
  triggerBlock('response_declare'),
  triggerBlock('equipment_any_turn_start'),
  triggerBlock('equipment_owner_turn_start'),
  triggerBlock('equipment_owner_turn_ready', { MIN_TURNS: numberShadow(1) }),
  triggerBlock('equipment_enemy_turn_start'),
  triggerBlock('equipment_damage_taken'),
  triggerBlock('equipment_manual_trigger'),
  triggerBlock('aura_enemy_elixir_recovery', { AMOUNT: numberShadow(-1) }),
  triggerBlock('passive_fatal_set_health_exile', { HEALTH: numberShadow(5) }),
  triggerBlock('counter_dodge', { AMOUNT: numberShadow(1) }),
  triggerBlock('counter_nazar'),
  triggerBlock('counter_equip_protect', { AMOUNT: numberShadow(1) }),
  triggerBlock('counter_negate_skill'),
  triggerBlock('counter_block_enemy_attacks', { DURATION: numberShadow(1) }),
  triggerBlock('counter_set_invincible_then_die'),
];

const TRIGGER_BLOCKS_BY_KIND = {
  cards: CARD_TRIGGER_BLOCKS,
  events: [triggerBlock('trigger_event_apply')],
  statuses: [triggerBlock('trigger_status_exists')],
  tags: [triggerBlock('trigger_tag_exists')],
  variables: [],
};

export function toolboxForKind(kind = 'cards') {
  const next = JSON.parse(JSON.stringify(toolbox));
  const triggerCategory = next.contents.find(category =>
    Array.isArray(category.contents)
    && category.contents.some(item => item && item.type === 'trigger_on_play')
  );
  if (triggerCategory) {
    triggerCategory.contents = TRIGGER_BLOCKS_BY_KIND[kind] || CARD_TRIGGER_BLOCKS;
  }
  return next;
}
