const numberShadow = value => ({ shadow: { type: 'math_number', fields: { NUM: value } } });

export const toolbox = {
  kind: 'categoryToolbox',
  contents: [
    {
      kind: 'category',
      name: '触发',
      colour: 24,
      contents: [
        { kind: 'block', type: 'trigger_on_play' },
        { kind: 'block', type: 'trigger_on_friendly_turn_start' },
        { kind: 'block', type: 'trigger_on_enemy_turn_start' },
        { kind: 'block', type: 'trigger_on_phys_damage' },
        { kind: 'block', type: 'trigger_on_any_damage' },
        { kind: 'block', type: 'trigger_on_destroy' },
        { kind: 'block', type: 'trigger_on_event' },
        { kind: 'block', type: 'trigger_manual' },
        { kind: 'block', type: 'response_declare' },
        { kind: 'block', type: 'event_owner_turn_start' },
        { kind: 'block', type: 'event_enemy_turn_start' },
        { kind: 'block', type: 'event_damage_taken' },
        { kind: 'block', type: 'event_equipment_trigger' },
        { kind: 'block', type: 'aura_enemy_elixir_recovery', inputs: { AMOUNT: numberShadow(-1) } },
        { kind: 'block', type: 'passive_fatal_set_health_exile', inputs: { HEALTH: numberShadow(5) } },
        { kind: 'block', type: 'counter_dodge', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'counter_nazar' },
        { kind: 'block', type: 'counter_equip_protect', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'counter_negate_skill' },
        { kind: 'block', type: 'counter_block_enemy_attacks', inputs: { DURATION: numberShadow(1) } },
        { kind: 'block', type: 'counter_set_invincible_then_die' },
      ],
    },
    {
      kind: 'category',
      name: '目标',
      colour: 55,
      contents: [
        { kind: 'block', type: 'target_self' },
        { kind: 'block', type: 'target_teammate' },
        { kind: 'block', type: 'target_friendly' },
        { kind: 'block', type: 'target_enemy' },
        { kind: 'block', type: 'target_all_enemies' },
        { kind: 'block', type: 'target_both' },
        { kind: 'block', type: 'target_random_friendly' },
        { kind: 'block', type: 'target_random_enemy' },
        { kind: 'block', type: 'target_random_player' },
        { kind: 'block', type: 'target_random_side' },
        { kind: 'block', type: 'target_event_target' },
        { kind: 'block', type: 'target_event_source' },
        { kind: 'block', type: 'target_last_actor' },
      ],
    },
    {
      kind: 'category',
      name: '伤害与回复',
      colour: 350,
      contents: [
        {
          kind: 'block',
          type: 'action_damage',
          inputs: { AMOUNT: numberShadow(6) },
        },
        {
          kind: 'block',
          type: 'action_damage_multi',
          inputs: {
            AMOUNT: numberShadow(2),
            TIMES: numberShadow(2),
          },
        },
        {
          kind: 'block',
          type: 'action_direct_damage',
          inputs: { AMOUNT: numberShadow(1) },
        },
        {
          kind: 'block',
          type: 'action_lifesteal_damage',
          inputs: {
            AMOUNT: numberShadow(8),
            HEAL: numberShadow(4),
          },
        },
        { kind: 'block', type: 'action_heal', inputs: { AMOUNT: numberShadow(4) } },
        { kind: 'block', type: 'action_set_health', inputs: { AMOUNT: numberShadow(20) } },
        { kind: 'block', type: 'action_add_armor', inputs: { AMOUNT: numberShadow(2) } },
        { kind: 'block', type: 'action_remove_armor', inputs: { AMOUNT: numberShadow(2) } },
        { kind: 'block', type: 'action_set_armor', inputs: { AMOUNT: numberShadow(0) } },
        { kind: 'block', type: 'action_dodge_this' },
        { kind: 'block', type: 'action_dodge_permanent', inputs: { AMOUNT: numberShadow(1) } },
      ],
    },
    {
      kind: 'category',
      name: '状态与标签',
      colour: 300,
      contents: [
        { kind: 'block', type: 'action_poison', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_burn', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_vulnus', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_toxic', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_status_add_named', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_status_remove_named' },
        { kind: 'block', type: 'action_tag_add_named' },
        { kind: 'block', type: 'action_tag_remove_named' },
        { kind: 'block', type: 'action_add_tag' },
        { kind: 'block', type: 'action_remove_tag' },
        { kind: 'block', type: 'action_clear_buffs' },
        { kind: 'block', type: 'action_clear_debuffs' },
        { kind: 'block', type: 'action_clear_all_effects' },
        { kind: 'block', type: 'action_clear_status' },
      ],
    },
    {
      kind: 'category',
      name: '资源与牌堆',
      colour: 185,
      contents: [
        { kind: 'block', type: 'action_gain_e', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_gain_m', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_cost_e', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_cost_m', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_mod_e_regen', inputs: { AMOUNT: numberShadow(-1) } },
        { kind: 'block', type: 'action_mod_m_regen', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_mod_draw', inputs: { AMOUNT: numberShadow(-1) } },
        { kind: 'block', type: 'action_draw', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_discard', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_discard_choice_then_draw' },
        { kind: 'block', type: 'action_choose_from_deck' },
        { kind: 'block', type: 'action_choose_from_discard' },
        { kind: 'block', type: 'action_choose_from_exile' },
        { kind: 'block', type: 'action_reveal_hand' },
        { kind: 'block', type: 'action_steal_card' },
      ],
    },
    {
      kind: 'category',
      name: '装备与限制',
      colour: 220,
      contents: [
        { kind: 'block', type: 'action_destroy_random_equip' },
        { kind: 'block', type: 'action_destroy_all_equip' },
        { kind: 'block', type: 'action_destroy_all_field_equip' },
        { kind: 'block', type: 'action_destroy_equipment_choice_or_first' },
        { kind: 'block', type: 'action_destroy_all_destroyable_equipment' },
        { kind: 'block', type: 'action_equip_disc_armor', inputs: { AMOUNT: numberShadow(2) } },
        { kind: 'block', type: 'action_equip_sponge' },
        { kind: 'block', type: 'action_equip_set_health', inputs: { AMOUNT: numberShadow(60) } },
        { kind: 'block', type: 'action_equip_reduce_own_draw', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_equip_reduce_own_e', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_equip_on_destroy_remove_poison_damage', inputs: { MULTIPLIER: numberShadow(2) } },
        { kind: 'block', type: 'action_activate_corruption' },
        { kind: 'block', type: 'action_magic_battery_gain_m', inputs: { AMOUNT: numberShadow(1), LIMIT: numberShadow(3) } },
        { kind: 'block', type: 'action_destroy_self_equipment' },
        { kind: 'block', type: 'action_equip_protection' },
        { kind: 'block', type: 'action_remove_equip_protection' },
        { kind: 'block', type: 'action_place_as_equip' },
        { kind: 'block', type: 'action_block_action' },
        { kind: 'block', type: 'action_block_card_type', inputs: { DURATION: numberShadow(1) } },
        { kind: 'block', type: 'action_force_card_type', inputs: { DURATION: numberShadow(1) } },
        { kind: 'block', type: 'action_nullify_current_card' },
        { kind: 'block', type: 'action_invincible' },
        { kind: 'block', type: 'action_untargetable' },
        { kind: 'block', type: 'action_skip_turn' },
        { kind: 'block', type: 'action_extra_turn' },
        { kind: 'block', type: 'action_force_end_turn' },
      ],
    },
    {
      kind: 'category',
      name: '卡牌操作',
      colour: 260,
      contents: [
        { kind: 'block', type: 'action_fission', inputs: { TIMES: numberShadow(2) } },
        { kind: 'block', type: 'action_fusion', inputs: { MIN_COUNT: numberShadow(2), MAX_COUNT: numberShadow(3) } },
        { kind: 'block', type: 'action_multiply_next_damage', inputs: { MULTIPLIER: numberShadow(2) } },
        { kind: 'block', type: 'action_reduce_next_cost', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_increase_next_cost', inputs: { AMOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_transform_card' },
        { kind: 'block', type: 'action_copy_card' },
        { kind: 'block', type: 'action_copy_choice_with_discount', inputs: { DISCOUNT: numberShadow(1) } },
        { kind: 'block', type: 'action_give_card_to_hand' },
        { kind: 'block', type: 'action_remove_specific_card' },
        { kind: 'block', type: 'action_exile_this' },
        { kind: 'block', type: 'action_move_to_discard' },
        { kind: 'block', type: 'action_move_to_deck' },
      ],
    },
    {
      kind: 'category',
      name: '变量',
      colour: 32,
      contents: [
        { kind: 'block', type: 'value_var' },
        { kind: 'block', type: 'condition_var_compare', inputs: { VALUE: numberShadow(0) } },
        { kind: 'block', type: 'action_var_set', inputs: { VALUE: numberShadow(0) } },
        { kind: 'block', type: 'action_var_add', inputs: { VALUE: numberShadow(1) } },
        { kind: 'block', type: 'action_var_sub', inputs: { VALUE: numberShadow(1) } },
        { kind: 'block', type: 'action_var_mul', inputs: { VALUE: numberShadow(2) } },
        { kind: 'block', type: 'action_var_div', inputs: { VALUE: numberShadow(2) } },
        { kind: 'block', type: 'action_batch_var_add', inputs: { VALUE: numberShadow(1) } },
        { kind: 'block', type: 'action_batch_var_sub', inputs: { VALUE: numberShadow(1) } },
      ],
    },
    {
      kind: 'category',
      name: '逻辑与数值',
      colour: 120,
      contents: [
        { kind: 'block', type: 'control_if' },
        { kind: 'block', type: 'control_if_else' },
        { kind: 'block', type: 'control_repeat', inputs: { TIMES: numberShadow(2) } },
        { kind: 'block', type: 'control_for_each' },
        { kind: 'block', type: 'control_random' },
        { kind: 'block', type: 'condition_compare', inputs: { A: numberShadow(0), B: numberShadow(0) } },
        { kind: 'block', type: 'condition_has_status_named' },
        { kind: 'block', type: 'condition_has_tag' },
        { kind: 'block', type: 'condition_target_attribute', inputs: { VALUE: numberShadow(0) } },
        { kind: 'block', type: 'condition_and_or' },
        { kind: 'block', type: 'condition_not' },
        { kind: 'block', type: 'raw_effect_json' },
        { kind: 'block', type: 'value_target_attribute' },
        { kind: 'block', type: 'value_incoming_damage' },
        { kind: 'block', type: 'value_last_damage' },
        { kind: 'block', type: 'value_status_count' },
        {
          kind: 'block',
          type: 'value_math_op',
          inputs: {
            A: numberShadow(0),
            B: numberShadow(0),
          },
        },
        {
          kind: 'block',
          type: 'value_round',
          inputs: { VALUE: numberShadow(0) },
        },
        {
          kind: 'block',
          type: 'value_min_max',
          inputs: {
            A: numberShadow(0),
            B: numberShadow(0),
          },
        },
        {
          kind: 'block',
          type: 'value_random',
          inputs: {
            MIN: numberShadow(1),
            MAX: numberShadow(10),
          },
        },
      ],
    },
    { kind: 'sep' },
    { kind: 'category', name: '自定义过程', custom: 'PROCEDURE', colour: 285 },
  ],
};
